### PR TITLE
Use future to support input as string on both python 2 and 3

### PR DESCRIPTION
**Pull request by Giannie**
Import input from the builtins module provided by the future package to support raw_input style input in python 2. This addresses issue #40.

### CODE REVIEW

**Comment by letorbi** [comment]
Thanks for the PR, but I'd prefer to use a simple logical operation instead of introducing an extra dependency. As far as I see, something like:

```
confirmation = (raw_input or input)("Enter 'yes' to continue or anything else to cancel: ")
```

would be sufficient to make the code compatible with Python 2 and 3. Or am I missing something here?

**Comment by Giannie** [comment]
That’s fair. But for full cross compatibility between 2 and 3, future is a very sensible dependency. It allows for compatibility of various built in functions including print. If you’d like to keep cross compatibility, future is a very sensible dependency as it is the essential purpose of the library.

**Comment by letorbi** [comment]
Thanks for the hint. I'll take a deeper look into the *futures* package and might reconsider my position.

**Comment by letorbi** [comment]
I've checked through the features that the *future* package provides and only `input`, `range` and `unicode_literals` are of some relevance for the Synoindex Watcher code.

`input` will most likely be removed from the codebase soon. `range` is used one time for a for-loop, which is no critical use-case regarding the changes between Python 2 and 3. `unicode_literals` might be useful, but the underlying *inotifyrecursive* and *inotify-simple* packages already handle Python 2 and Python 3 strings correctly. There were issues about unicode-compatibility (https://github.com/letorbi/inotifyrecursive/issues/6 and https://github.com/letorbi/inotifyrecursive/issues/7), but they have been fixed.

So for now I don't see a need for the *futures* package, but I will keep it in mind, if I ran into compatibility issues again. Thanks for pointing me to it and also thanks for the PR.

**Pull request closed without merging**
